services:
    _defaults:
        public: true

    CoreShop\Bundle\OrderReturnBundle\Renderer\Pdf\MpdfRenderer:
        arguments:
            - '%kernel.cache_dir%'

    CoreShop\Bundle\OrderBundleReturn\Renderer\Pdf\PdfRendererInterface:
        alias: 'CoreShop\Bundle\OrderReturnBundle\Renderer\Pdf\MpdfRenderer'