services:
    CoreShop\Bundle\OrderReturnBundle\Twig\OrderReturnDateExtension:
        arguments:
            - '@CoreShop\Component\Locale\Context\LocaleContextInterface'
        tags:
            - { name: twig.extension }
