core_shop_order_return:
    resources:
        order_return:
            classes:
                model: CoreShop\Component\OrderReturn\Model\OrderReturn
                interface: CoreShop\Component\OrderReturn\Model\OrderReturnInterface
    pimcore:
        order_return:
            classes:
                model: Pimcore\Model\DataObject\CoreShopOrderReturn
                interface: CoreShop\Component\OrderReturn\Model\OrderReturnInterface
                install_file: '@CoreShopOrderReturnBundle/Resources/install/pimcore/classes/CoreShopOrderReturn.json'
